/**
 *
 * @file GPIO_Enum.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 5 feb. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 5 feb. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef GPIO_PERIPHERAL_HEADER_GPIO_ENUM_H_
#define GPIO_PERIPHERAL_HEADER_GPIO_ENUM_H_

#include "DriverLib/MCU/Header/MCU_Common.h"

typedef enum
{
    GPIO_enPORT1 = 0U,
    GPIO_enPORT2 = 1U,
    GPIO_enPORT3 = 2U,
    GPIO_enPORT4 = 3U,
    GPIO_enPORT5 = 4U,
    GPIO_enPORT6 = 5U,
    GPIO_enPORT_MAX = 6U,
}GPIO_nPORT;

typedef enum
{
    GPIO_enPIN_NUMBER0 = 0U,
    GPIO_enPIN_NUMBER1 = 1U,
    GPIO_enPIN_NUMBER2 = 2U,
    GPIO_enPIN_NUMBER3 = 3U,
    GPIO_enPIN_NUMBER4 = 4U,
    GPIO_enPIN_NUMBER5 = 5U,
    GPIO_enPIN_NUMBER6 = 6U,
    GPIO_enPIN_NUMBER7 = 7U,
    GPIO_enPIN_NUMBER_MAX = 8U,
}GPIO_nPIN_NUMBER;

typedef enum
{
    GPIO_enPIN_NONE = 0x0U,
    GPIO_enPIN0 = 0x1U,
    GPIO_enPIN1 = 0x2U,
    GPIO_enPIN2 = 0x4U,
    GPIO_enPIN3 = 0x8U,
    GPIO_enPIN4 = 0x10U,
    GPIO_enPIN5 = 0x20U,
    GPIO_enPIN6 = 0x40U,
    GPIO_enPIN7 = 0x80U,
    GPIO_enPIN_ALL = 0xFFU,
}GPIO_nPIN;

typedef enum
{
    GPIO_enDIR_INPUT = 0U,
    GPIO_enDIR_OUTPUT = 1U,
}GPIO_nDIR;

typedef enum
{
    GPIO_enSEL_IO = 0U,
    GPIO_enSEL_PERIPHERAL = 1U,
}GPIO_nSEL;

typedef enum
{
    GPIO_enLEVEL_LOW = 0U,
    GPIO_enLEVEL_HIGH = 1U,
}GPIO_nLEVEL;

typedef enum
{
    GPIO_enINT_ENABLE_DIS = 0U,
    GPIO_enINT_ENABLE_ENA = 1U,
}GPIO_nINT_ENABLE;

typedef enum
{
    GPIO_enINT_STATUS_NOOCCUR = 0U,
    GPIO_enINT_STATUS_OCCUR = 1U,
}GPIO_nINT_STATUS;

typedef enum
{
    GPIO_enINT_EDGE_RISING = 0U,
    GPIO_enINT_EDGE_FALLING = 1U,
}GPIO_nINT_EDGE;


#define GPIO_PIN_MASK (0xFU)
#define GPIO_PORT_MASK (0xFU)
#define GPIO_SEL_MASK (0xFU)
#define GPIO_DIR_MASK (0xFU)
#define GPIO_PIN_OFFSET (0U)
#define GPIO_PORT_OFFSET (4U)
#define GPIO_SEL_OFFSET (8U)
#define GPIO_DIR_OFFSET (12U)


/*PORT PIN VALUE*/
typedef enum
{
    /*PORT1*/
    GPIO_enPORT10 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER0 << GPIO_PIN_OFFSET)),
    GPIO_enTA_CLK  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER0 << GPIO_PIN_OFFSET)),

    GPIO_enPORT11 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),
    GPIO_enTA_OUT0_P11  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),
    GPIO_enTA_CCI0A  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),

    GPIO_enPORT12 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),
    GPIO_enTA_OUT1_P12  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),
    GPIO_enTA_CCI1A  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),

    GPIO_enPORT13 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),
    GPIO_enTA_OUT2_P13  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),
    GPIO_enTA_CCI2A  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),

    GPIO_enPORT14 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),
    GPIO_enSMCLK_P14  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),

    GPIO_enPORT15 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER5 << GPIO_PIN_OFFSET)),
    GPIO_enTA_OUT0_P15  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER5 << GPIO_PIN_OFFSET)),

    GPIO_enPORT16 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),
    GPIO_enTA_OUT1_P16  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),

    GPIO_enPORT17 = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),
    GPIO_enTA_OUT2_P17  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT1 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),

    /*PORT2*/
    GPIO_enPORT20 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER0 << GPIO_PIN_OFFSET)),
    GPIO_enACLK_P20  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER0 << GPIO_PIN_OFFSET)),

    GPIO_enPORT21 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),
    GPIO_enTA_INCLK  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),

    GPIO_enPORT22 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),
    GPIO_enCA_OUT  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),
    GPIO_enTA_CCI0B  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),

    GPIO_enPORT23 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),
    GPIO_enTA_OUT1_P23  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),
    GPIO_enCA0  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),

    GPIO_enPORT24 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),
    GPIO_enTA_OUT2_P24  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),
    GPIO_enCA1  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),

    GPIO_enPORT25 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER5 << GPIO_PIN_OFFSET)),
    GPIO_enROSC  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER5 << GPIO_PIN_OFFSET)),

    GPIO_enPORT26 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),
    GPIO_enADC12CLK  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),
    GPIO_enDMAE0  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),

    GPIO_enPORT27 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),
    GPIO_enTA_OUT0_P27  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT2 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),

    /*PORT3*/
    GPIO_enPORT30 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER0 << GPIO_PIN_OFFSET)),
    GPIO_enSTE0  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER0 << GPIO_PIN_OFFSET)),

    GPIO_enPORT31 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),
    GPIO_enMOSI0  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),
    GPIO_enSDA  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),

    GPIO_enPORT32 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),
    GPIO_enMISO0  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),

    GPIO_enPORT33 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),
    GPIO_enUCLK0  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),
    GPIO_enSCL  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),

    GPIO_enPORT34 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),
    GPIO_enUTXD0  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),

    GPIO_enPORT35 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER5 << GPIO_PIN_OFFSET)),
    GPIO_enURXD0  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER5 << GPIO_PIN_OFFSET)),

    GPIO_enPORT36 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),
    GPIO_enUTXD1  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),

    GPIO_enPORT37 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),
    GPIO_enURXD1  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT3 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),

    /*PORT4*/
    GPIO_enPORT40 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER0 << GPIO_PIN_OFFSET)),
    GPIO_enTB_OUT0  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER0 << GPIO_PIN_OFFSET)),
    GPIO_enTB_CCI0A  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER0 << GPIO_PIN_OFFSET)),
    GPIO_enTB_CCI0B  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER0 << GPIO_PIN_OFFSET)),

    GPIO_enPORT41 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),
    GPIO_enTB_OUT1  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),
    GPIO_enTB_CCI1A  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),
    GPIO_enTB_CCI1B  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),

    GPIO_enPORT42 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),
    GPIO_enTB_OUT2  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),
    GPIO_enTB_CCI2A  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),
    GPIO_enTB_CCI2B  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),

    GPIO_enPORT43 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),
    GPIO_enTB_OUT3  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),
    GPIO_enTB_CCI3A  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),
    GPIO_enTB_CCI3B  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),

    GPIO_enPORT44 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),
    GPIO_enTB_OUT4  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),
    GPIO_enTB_CCI4A  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),
    GPIO_enTB_CCI4B  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),

    GPIO_enPORT45 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER5 << GPIO_PIN_OFFSET)),
    GPIO_enTB_OUT5  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER5 << GPIO_PIN_OFFSET)),
    GPIO_enTB_CCI5A  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER5 << GPIO_PIN_OFFSET)),
    GPIO_enTB_CCI5B  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER5 << GPIO_PIN_OFFSET)),

    GPIO_enPORT46 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),
    GPIO_enTB_OUT6  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),
    GPIO_enTB_CCI6A  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),

    GPIO_enPORT47 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),
    GPIO_enTB_CLK  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT4 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),

    /*PORT5*/
    GPIO_enPORT50 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER0 << GPIO_PIN_OFFSET)),
    GPIO_enSTE1  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER0 << GPIO_PIN_OFFSET)),

    GPIO_enPORT51 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),
    GPIO_enMOSI1  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),

    GPIO_enPORT52 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),
    GPIO_enMISO1  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),

    GPIO_enPORT53 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),
    GPIO_enUCLK1  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),

    GPIO_enPORT54 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),
    GPIO_enMCLK  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),

    GPIO_enPORT55 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER5 << GPIO_PIN_OFFSET)),
    GPIO_enSMCLK_P55  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER5 << GPIO_PIN_OFFSET)),

    GPIO_enPORT56 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),
    GPIO_enACLK_P56  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),

    GPIO_enPORT57 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),
    GPIO_enSVSOUT  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),
    GPIO_enTB_OUTHiZ  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT5 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),

    /*PORT6*/
    GPIO_enPORT60 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER0 << GPIO_PIN_OFFSET)),
    GPIO_enA0  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER0 << GPIO_PIN_OFFSET)),

    GPIO_enPORT61 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),
    GPIO_enA1  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER1 << GPIO_PIN_OFFSET)),

    GPIO_enPORT62 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),
    GPIO_enA2  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER2 << GPIO_PIN_OFFSET)),

    GPIO_enPORT63 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),
    GPIO_enA3  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER3 << GPIO_PIN_OFFSET)),

    GPIO_enPORT64 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),
    GPIO_enA4  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER4 << GPIO_PIN_OFFSET)),

    GPIO_enPORT65 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER5 << GPIO_PIN_OFFSET)),
    GPIO_enA5  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER5 << GPIO_PIN_OFFSET)),

    GPIO_enPORT66 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),
    GPIO_enA6  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),
    GPIO_enDAC0  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER6 << GPIO_PIN_OFFSET)),

    GPIO_enPORT67 = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_IO << GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),
    GPIO_enA7  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),
    GPIO_enDAC1  = (uint16_t) (((uint16_t) GPIO_enDIR_OUTPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),
    GPIO_enSVSIN  = (uint16_t) (((uint16_t) GPIO_enDIR_INPUT << GPIO_DIR_OFFSET) | ((uint16_t) GPIO_enSEL_PERIPHERAL <<GPIO_SEL_OFFSET) | ((uint16_t) GPIO_enPORT6 << GPIO_PORT_OFFSET) | ((uint16_t) GPIO_enPIN_NUMBER7 << GPIO_PIN_OFFSET)),

    GPIO_enGPIO_UNDEF = 0xFFFFUL,
} GPIO_nDIGITAL_FUNCTION;



typedef MCU_Register8Bits_t GPIO_Register_t;

#endif /* GPIO_PERIPHERAL_HEADER_GPIO_ENUM_H_ */
