/**
 *
 * @file DMA_RegisterDefines_CH_CTL.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 6 feb. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 6 feb. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DMA_PERIPHERAL_REGISTERDEFINES_HEADER_DMA_REGISTERDEFINES_CH_CTL_H_
#define DMA_PERIPHERAL_REGISTERDEFINES_HEADER_DMA_REGISTERDEFINES_CH_CTL_H_

#include "DriverLib/MCU/Header/MCU_Common.h"

/******************************************************************************************
 ************************************ 3 CH_CTL *********************************************
 ******************************************************************************************/
/*-----------*/
#define DMA_CH_CTL_R_REQ_BIT ((uint8_t) 0U)

#define DMA_CH_CTL_REQ_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_REQ_NA ((uint8_t) 0x00U)
#define DMA_CH_CTL_REQ_REQUEST ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_REQ_MASK (DMA_CH_CTL_REQ_MASK << DMA_CH_CTL_R_REQ_BIT)
#define DMA_CH_CTL_R_REQ_NA (DMA_CH_CTL_REQ_NA << DMA_CH_CTL_R_REQ_BIT)
#define DMA_CH_CTL_R_REQ_REQUEST (DMA_CH_CTL_REQ_REQUEST << DMA_CH_CTL_R_REQ_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_ABORT_BIT ((uint8_t) 1U)

#define DMA_CH_CTL_ABORT_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_ABORT_NA ((uint8_t) 0x00U)
#define DMA_CH_CTL_ABORT_ABORTED ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_ABORT_MASK (DMA_CH_CTL_ABORT_MASK << DMA_CH_CTL_R_ABORT_BIT)
#define DMA_CH_CTL_R_ABORT_NA (DMA_CH_CTL_ABORT_NA << DMA_CH_CTL_R_ABORT_BIT)
#define DMA_CH_CTL_R_ABORT_ABORTED (DMA_CH_CTL_ABORT_ABORTED << DMA_CH_CTL_R_ABORT_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_IE_BIT ((uint8_t) 2U)

#define DMA_CH_CTL_IE_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_IE_DIS ((uint8_t) 0x00U)
#define DMA_CH_CTL_IE_ENA ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_IE_MASK (DMA_CH_CTL_IE_MASK << DMA_CH_CTL_R_IE_BIT)
#define DMA_CH_CTL_R_IE_DIS (DMA_CH_CTL_IE_DIS << DMA_CH_CTL_R_IE_BIT)
#define DMA_CH_CTL_R_IE_ENA (DMA_CH_CTL_IE_ENA << DMA_CH_CTL_R_IE_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_IFG_BIT ((uint8_t) 3U)

#define DMA_CH_CTL_IFG_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_IFG_NOOCCUR ((uint8_t) 0x00U)
#define DMA_CH_CTL_IFG_OCCUR ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_IFG_MASK (DMA_CH_CTL_IFG_MASK << DMA_CH_CTL_R_IFG_BIT)
#define DMA_CH_CTL_R_IFG_NOOCCUR (DMA_CH_CTL_IFG_NOOCCUR << DMA_CH_CTL_R_IFG_BIT)
#define DMA_CH_CTL_R_IFG_OCCUR (DMA_CH_CTL_IFG_OCCUR << DMA_CH_CTL_R_IFG_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_EN_BIT ((uint8_t) 4U)

#define DMA_CH_CTL_EN_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_EN_DIS ((uint8_t) 0x00U)
#define DMA_CH_CTL_EN_ENA ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_EN_MASK (DMA_CH_CTL_EN_MASK << DMA_CH_CTL_R_EN_BIT)
#define DMA_CH_CTL_R_EN_DIS (DMA_CH_CTL_EN_DIS << DMA_CH_CTL_R_EN_BIT)
#define DMA_CH_CTL_R_EN_ENA (DMA_CH_CTL_EN_ENA << DMA_CH_CTL_R_EN_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_LEVEL_BIT ((uint8_t) 5U)

#define DMA_CH_CTL_LEVEL_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_LEVEL_EDGE ((uint8_t) 0x00U)
#define DMA_CH_CTL_LEVEL_LEVEL ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_LEVEL_MASK (DMA_CH_CTL_LEVEL_MASK << DMA_CH_CTL_R_LEVEL_BIT)
#define DMA_CH_CTL_R_LEVEL_EDGE (DMA_CH_CTL_LEVEL_EDGE << DMA_CH_CTL_R_LEVEL_BIT)
#define DMA_CH_CTL_R_LEVEL_LEVEL (DMA_CH_CTL_LEVEL_LEVEL << DMA_CH_CTL_R_LEVEL_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_SRCBYTE_BIT ((uint8_t) 6U)

#define DMA_CH_CTL_SRCBYTE_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_SRCBYTE_WORD ((uint8_t) 0x00U)
#define DMA_CH_CTL_SRCBYTE_BYTE ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_SRCBYTE_MASK (DMA_CH_CTL_SRCBYTE_MASK << DMA_CH_CTL_R_SRCBYTE_BIT)
#define DMA_CH_CTL_R_SRCBYTE_WORD (DMA_CH_CTL_SRCBYTE_WORD << DMA_CH_CTL_R_SRCBYTE_BIT)
#define DMA_CH_CTL_R_SRCBYTE_BYTE (DMA_CH_CTL_SRCBYTE_BYTE << DMA_CH_CTL_R_SRCBYTE_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_DSTBYTE_BIT ((uint8_t) 7U)

#define DMA_CH_CTL_DSTBYTE_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_DSTBYTE_WORD ((uint8_t) 0x00U)
#define DMA_CH_CTL_DSTBYTE_BYTE ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_DSTBYTE_MASK (DMA_CH_CTL_DSTBYTE_MASK << DMA_CH_CTL_R_DSTBYTE_BIT)
#define DMA_CH_CTL_R_DSTBYTE_WORD (DMA_CH_CTL_DSTBYTE_WORD << DMA_CH_CTL_R_DSTBYTE_BIT)
#define DMA_CH_CTL_R_DSTBYTE_BYTE (DMA_CH_CTL_DSTBYTE_BYTE << DMA_CH_CTL_R_DSTBYTE_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_SRCINCR_BIT ((uint8_t) 8U)

#define DMA_CH_CTL_SRCINCR_MASK ((uint8_t) 0x03U)
#define DMA_CH_CTL_SRCINCR_UNCHANGED ((uint8_t) 0x00U)
#define DMA_CH_CTL_SRCINCR_UNCHANGED1 ((uint8_t) 0x01U)
#define DMA_CH_CTL_SRCINCR_DECREMENT ((uint8_t) 0x02U)
#define DMA_CH_CTL_SRCINCR_INCREMENT ((uint8_t) 0x03U)

#define DMA_CH_CTL_R_SRCINCR_MASK (DMA_CH_CTL_SRCINCR_MASK << DMA_CH_CTL_R_SRCINCR_BIT)
#define DMA_CH_CTL_R_SRCINCR_UNCHANGED (DMA_CH_CTL_SRCINCR_UNCHANGED << DMA_CH_CTL_R_SRCINCR_BIT)
#define DMA_CH_CTL_R_SRCINCR_UNCHANGED1 (DMA_CH_CTL_SRCINCR_UNCHANGED1 << DMA_CH_CTL_R_SRCINCR_BIT)
#define DMA_CH_CTL_R_SRCINCR_DECREMENT (DMA_CH_CTL_SRCINCR_DECREMENT << DMA_CH_CTL_R_SRCINCR_BIT)
#define DMA_CH_CTL_R_SRCINCR_INCREMENT (DMA_CH_CTL_SRCINCR_INCREMENT << DMA_CH_CTL_R_SRCINCR_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_DSTINCR_BIT ((uint8_t) 10U)

#define DMA_CH_CTL_DSTINCR_MASK ((uint8_t) 0x03U)
#define DMA_CH_CTL_DSTINCR_UNCHANGED ((uint8_t) 0x00U)
#define DMA_CH_CTL_DSTINCR_UNCHANGED1 ((uint8_t) 0x01U)
#define DMA_CH_CTL_DSTINCR_DECREMENT ((uint8_t) 0x02U)
#define DMA_CH_CTL_DSTINCR_INCREMENT ((uint8_t) 0x03U)

#define DMA_CH_CTL_R_DSTINCR_MASK (DMA_CH_CTL_DSTINCR_MASK << DMA_CH_CTL_R_DSTINCR_BIT)
#define DMA_CH_CTL_R_DSTINCR_UNCHANGED (DMA_CH_CTL_DSTINCR_UNCHANGED << DMA_CH_CTL_R_DSTINCR_BIT)
#define DMA_CH_CTL_R_DSTINCR_UNCHANGED1 (DMA_CH_CTL_DSTINCR_UNCHANGED1 << DMA_CH_CTL_R_DSTINCR_BIT)
#define DMA_CH_CTL_R_DSTINCR_DECREMENT (DMA_CH_CTL_DSTINCR_DECREMENT << DMA_CH_CTL_R_DSTINCR_BIT)
#define DMA_CH_CTL_R_DSTINCR_INCREMENT (DMA_CH_CTL_DSTINCR_INCREMENT << DMA_CH_CTL_R_DSTINCR_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_DT_BIT ((uint8_t) 12U)

#define DMA_CH_CTL_DT_MASK ((uint8_t) 0x07U)
#define DMA_CH_CTL_DT_SINGLE ((uint8_t) 0x00U)
#define DMA_CH_CTL_DT_BLOCK ((uint8_t) 0x01U)
#define DMA_CH_CTL_DT_BLOCK_BURST ((uint8_t) 0x02U)
#define DMA_CH_CTL_DT_BLOCK_BURST1 ((uint8_t) 0x03U)
#define DMA_CH_CTL_DT_REPEAT_SINGLE ((uint8_t) 0x04U)
#define DMA_CH_CTL_DT_REPEAT_BLOCK ((uint8_t) 0x05U)
#define DMA_CH_CTL_DT_REPEAT_BLOCK_BURST ((uint8_t) 0x06U)
#define DMA_CH_CTL_DT_REPEAT_BLOCK_BURST1 ((uint8_t) 0x07U)

#define DMA_CH_CTL_R_DT_MASK (DMA_CH_CTL_DT_MASK << DMA_CH_CTL_R_DT_BIT)
#define DMA_CH_CTL_R_DT_SINGLE (DMA_CH_CTL_DT_SINGLE << DMA_CH_CTL_R_DT_BIT)
#define DMA_CH_CTL_R_DT_BLOCK (DMA_CH_CTL_DT_BLOCK << DMA_CH_CTL_R_DT_BIT)
#define DMA_CH_CTL_R_DT_BLOCK_BURST (DMA_CH_CTL_DT_BLOCK_BURST << DMA_CH_CTL_R_DT_BIT)
#define DMA_CH_CTL_R_DT_BLOCK_BURST1 (DMA_CH_CTL_DT_BLOCK_BURST1 << DMA_CH_CTL_R_DT_BIT)
#define DMA_CH_CTL_R_DT_REPEAT_SINGLE (DMA_CH_CTL_DT_REPEAT_SINGLE << DMA_CH_CTL_R_DT_BIT)
#define DMA_CH_CTL_R_DT_REPEAT_BLOCK (DMA_CH_CTL_DT_REPEAT_BLOCK << DMA_CH_CTL_R_DT_BIT)
#define DMA_CH_CTL_R_DT_REPEAT_BLOCK_BURST (DMA_CH_CTL_DT_REPEAT_BLOCK_BURST << DMA_CH_CTL_R_DT_BIT)
#define DMA_CH_CTL_R_DT_REPEAT_BLOCK_BURST1 (DMA_CH_CTL_DT_REPEAT_BLOCK_BURST1 << DMA_CH_CTL_R_DT_BIT)
/*-----------*/


/*-----------*/
#define DMA_CH_CTL_R_PIN1_BIT ((uint8_t) 1U)

#define DMA_CH_CTL_PIN1_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_PIN1_RISING ((uint8_t) 0x00U)
#define DMA_CH_CTL_PIN1_FALLING ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_PIN1_MASK (DMA_CH_CTL_PIN1_MASK << DMA_CH_CTL_R_PIN1_BIT)
#define DMA_CH_CTL_R_PIN1_RISING (DMA_CH_CTL_PIN1_RISING << DMA_CH_CTL_R_PIN1_BIT)
#define DMA_CH_CTL_R_PIN1_FALLING (DMA_CH_CTL_PIN1_FALLING << DMA_CH_CTL_R_PIN1_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_PIN2_BIT ((uint8_t) 2U)

#define DMA_CH_CTL_PIN2_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_PIN2_RISING ((uint8_t) 0x00U)
#define DMA_CH_CTL_PIN2_FALLING ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_PIN2_MASK (DMA_CH_CTL_PIN2_MASK << DMA_CH_CTL_R_PIN2_BIT)
#define DMA_CH_CTL_R_PIN2_RISING (DMA_CH_CTL_PIN2_RISING << DMA_CH_CTL_R_PIN2_BIT)
#define DMA_CH_CTL_R_PIN2_FALLING (DMA_CH_CTL_PIN2_FALLING << DMA_CH_CTL_R_PIN2_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_PIN3_BIT ((uint8_t) 3U)

#define DMA_CH_CTL_PIN3_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_PIN3_RISING ((uint8_t) 0x00U)
#define DMA_CH_CTL_PIN3_FALLING ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_PIN3_MASK (DMA_CH_CTL_PIN3_MASK << DMA_CH_CTL_R_PIN3_BIT)
#define DMA_CH_CTL_R_PIN3_RISING (DMA_CH_CTL_PIN3_RISING << DMA_CH_CTL_R_PIN3_BIT)
#define DMA_CH_CTL_R_PIN3_FALLING (DMA_CH_CTL_PIN3_FALLING << DMA_CH_CTL_R_PIN3_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_PIN4_BIT ((uint8_t) 4U)

#define DMA_CH_CTL_PIN4_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_PIN4_RISING ((uint8_t) 0x00U)
#define DMA_CH_CTL_PIN4_FALLING ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_PIN4_MASK (DMA_CH_CTL_PIN4_MASK << DMA_CH_CTL_R_PIN4_BIT)
#define DMA_CH_CTL_R_PIN4_RISING (DMA_CH_CTL_PIN4_RISING << DMA_CH_CTL_R_PIN4_BIT)
#define DMA_CH_CTL_R_PIN4_FALLING (DMA_CH_CTL_PIN4_FALLING << DMA_CH_CTL_R_PIN4_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_PIN5_BIT ((uint8_t) 5U)

#define DMA_CH_CTL_PIN5_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_PIN5_RISING ((uint8_t) 0x00U)
#define DMA_CH_CTL_PIN5_FALLING ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_PIN5_MASK (DMA_CH_CTL_PIN5_MASK << DMA_CH_CTL_R_PIN5_BIT)
#define DMA_CH_CTL_R_PIN5_RISING (DMA_CH_CTL_PIN5_RISING << DMA_CH_CTL_R_PIN5_BIT)
#define DMA_CH_CTL_R_PIN5_FALLING (DMA_CH_CTL_PIN5_FALLING << DMA_CH_CTL_R_PIN5_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_PIN6_BIT ((uint8_t) 6U)

#define DMA_CH_CTL_PIN6_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_PIN6_RISING ((uint8_t) 0x00U)
#define DMA_CH_CTL_PIN6_FALLING ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_PIN6_MASK (DMA_CH_CTL_PIN6_MASK << DMA_CH_CTL_R_PIN6_BIT)
#define DMA_CH_CTL_R_PIN6_RISING (DMA_CH_CTL_PIN6_RISING << DMA_CH_CTL_R_PIN6_BIT)
#define DMA_CH_CTL_R_PIN6_FALLING (DMA_CH_CTL_PIN6_FALLING << DMA_CH_CTL_R_PIN6_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH_CTL_R_PIN7_BIT ((uint8_t) 7U)

#define DMA_CH_CTL_PIN7_MASK ((uint8_t) 0x01U)
#define DMA_CH_CTL_PIN7_RISING ((uint8_t) 0x00U)
#define DMA_CH_CTL_PIN7_FALLING ((uint8_t) 0x01U)

#define DMA_CH_CTL_R_PIN7_MASK (DMA_CH_CTL_PIN7_MASK << DMA_CH_CTL_R_PIN7_BIT)
#define DMA_CH_CTL_R_PIN7_RISING (DMA_CH_CTL_PIN7_RISING << DMA_CH_CTL_R_PIN7_BIT)
#define DMA_CH_CTL_R_PIN7_FALLING (DMA_CH_CTL_PIN7_FALLING << DMA_CH_CTL_R_PIN7_BIT)
/*-----------*/

#endif /* DMA_PERIPHERAL_REGISTERDEFINES_HEADER_DMA_REGISTERDEFINES_CH_CTL_H_ */
