/**
 *
 * @file DMA_RegisterDefines_CTL0.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 6 feb. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 6 feb. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DMA_PERIPHERAL_REGISTERDEFINES_HEADER_DMA_REGISTERDEFINES_CTL0_H_
#define DMA_PERIPHERAL_REGISTERDEFINES_HEADER_DMA_REGISTERDEFINES_CTL0_H_

#include "DriverLib/MCU/Header/MCU_Common.h"

/******************************************************************************************
 ************************************ 1 CTL0 *********************************************
 ******************************************************************************************/

#define DMA_CTL0_CHTSEL_MASK ((uint8_t) 0x0FU)
#define DMA_CTL0_CHTSEL_SW ((uint8_t) 0x00U)
#define DMA_CTL0_CHTSEL_TACCR2 ((uint8_t) 0x01U)
#define DMA_CTL0_CHTSEL_TBCCR2 ((uint8_t) 0x02U)
#define DMA_CTL0_CHTSEL_USART0_RX ((uint8_t) 0x03U)
#define DMA_CTL0_CHTSEL_USART0_TX ((uint8_t) 0x04U)
#define DMA_CTL0_CHTSEL_DAC12_0 ((uint8_t) 0x05U)
#define DMA_CTL0_CHTSEL_ADC12x ((uint8_t) 0x06U)
#define DMA_CTL0_CHTSEL_TACCR0 ((uint8_t) 0x07U)
#define DMA_CTL0_CHTSEL_TBCCR0 ((uint8_t) 0x08U)
#define DMA_CTL0_CHTSEL_USART1_RX ((uint8_t) 0x09U)
#define DMA_CTL0_CHTSEL_USART1_TX ((uint8_t) 0x0AU)
#define DMA_CTL0_CHTSEL_MULTIPLIER ((uint8_t) 0x0BU)
#define DMA_CTL0_CHTSEL_NO_TRIGGER0 ((uint8_t) 0x0CU)
#define DMA_CTL0_CHTSEL_NO_TRIGGER1 ((uint8_t) 0x0DU)
#define DMA_CTL0_CHTSEL_DMA ((uint8_t) 0x0EU)
#define DMA_CTL0_CHTSEL_EXTERNAL ((uint8_t) 0x0FU)

/*-----------*/
#define DMA_CTL0_R_CH0TSEL_BIT ((uint8_t) 0U)

#define DMA_CTL0_CH0TSEL_MASK ((uint8_t) 0x0FU)
#define DMA_CTL0_CH0TSEL_SW ((uint8_t) 0x00U)
#define DMA_CTL0_CH0TSEL_TACCR2 ((uint8_t) 0x01U)
#define DMA_CTL0_CH0TSEL_TBCCR2 ((uint8_t) 0x02U)
#define DMA_CTL0_CH0TSEL_USART0_RX ((uint8_t) 0x03U)
#define DMA_CTL0_CH0TSEL_USART0_TX ((uint8_t) 0x04U)
#define DMA_CTL0_CH0TSEL_DAC12_0 ((uint8_t) 0x05U)
#define DMA_CTL0_CH0TSEL_ADC12x ((uint8_t) 0x06U)
#define DMA_CTL0_CH0TSEL_TACCR0 ((uint8_t) 0x07U)
#define DMA_CTL0_CH0TSEL_TBCCR0 ((uint8_t) 0x08U)
#define DMA_CTL0_CH0TSEL_USART1_RX ((uint8_t) 0x09U)
#define DMA_CTL0_CH0TSEL_USART1_TX ((uint8_t) 0x0AU)
#define DMA_CTL0_CH0TSEL_MULTIPLIER ((uint8_t) 0x0BU)
#define DMA_CTL0_CH0TSEL_NO_TRIGGER0 ((uint8_t) 0x0CU)
#define DMA_CTL0_CH0TSEL_NO_TRIGGER1 ((uint8_t) 0x0DU)
#define DMA_CTL0_CH0TSEL_DMA ((uint8_t) 0x0EU)
#define DMA_CTL0_CH0TSEL_EXTERNAL ((uint8_t) 0x0FU)

#define DMA_CTL0_R_CH0TSEL_MASK (DMA_CTL0_CH0TSEL_MASK << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_SW (DMA_CTL0_CH0TSEL_SW << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_TACCR2 (DMA_CTL0_CH0TSEL_TACCR2 << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_TBCCR2 (DMA_CTL0_CH0TSEL_TBCCR2 << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_USART0_RX (DMA_CTL0_CH0TSEL_USART0_RX << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_USART0_TX (DMA_CTL0_CH0TSEL_USART0_TX << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_DAC12_0 (DMA_CTL0_CH0TSEL_DAC12_0 << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_ADC12x (DMA_CTL0_CH0TSEL_ADC12x << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_TACCR0 (DMA_CTL0_CH0TSEL_TACCR0 << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_TBCCR0 (DMA_CTL0_CH0TSEL_TBCCR0 << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_USART1_RX (DMA_CTL0_CH0TSEL_USART1_RX << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_USART1_TX (DMA_CTL0_CH0TSEL_USART1_TX << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_MULTIPLIER (DMA_CTL0_CH0TSEL_MULTIPLIER << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_NO_TRIGGER0 (DMA_CTL0_CH0TSEL_NO_TRIGGER0 << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_NO_TRIGGER1 (DMA_CTL0_CH0TSEL_NO_TRIGGER1 << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_DMA (DMA_CTL0_CH0TSEL_DMA << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_EXTERNAL (DMA_CTL0_CH0TSEL_EXTERNAL << DMA_CTL0_R_CH0TSEL_BIT)
/*-----------*/

/*-----------*/
#define DMA_CTL0_R_CH1TSEL_BIT ((uint8_t) 4U)

#define DMA_CTL0_CH1TSEL_MASK ((uint8_t) 0x0FU)
#define DMA_CTL0_CH1TSEL_SW ((uint8_t) 0x00U)
#define DMA_CTL0_CH1TSEL_TACCR2 ((uint8_t) 0x01U)
#define DMA_CTL0_CH1TSEL_TBCCR2 ((uint8_t) 0x02U)
#define DMA_CTL0_CH1TSEL_USART0_RX ((uint8_t) 0x03U)
#define DMA_CTL0_CH1TSEL_USART0_TX ((uint8_t) 0x04U)
#define DMA_CTL0_CH1TSEL_DAC12_0 ((uint8_t) 0x05U)
#define DMA_CTL0_CH1TSEL_ADC12x ((uint8_t) 0x06U)
#define DMA_CTL0_CH1TSEL_TACCR0 ((uint8_t) 0x07U)
#define DMA_CTL0_CH1TSEL_TBCCR0 ((uint8_t) 0x08U)
#define DMA_CTL0_CH1TSEL_USART1_RX ((uint8_t) 0x09U)
#define DMA_CTL0_CH1TSEL_USART1_TX ((uint8_t) 0x0AU)
#define DMA_CTL0_CH1TSEL_MULTIPLIER ((uint8_t) 0x0BU)
#define DMA_CTL0_CH1TSEL_NO_TRIGGER0 ((uint8_t) 0x0CU)
#define DMA_CTL0_CH1TSEL_NO_TRIGGER1 ((uint8_t) 0x0DU)
#define DMA_CTL0_CH1TSEL_DMA ((uint8_t) 0x0EU)
#define DMA_CTL0_CH1TSEL_EXTERNAL ((uint8_t) 0x0FU)

#define DMA_CTL0_R_CH1TSEL_MASK (DMA_CTL0_CH1TSEL_MASK << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_SW (DMA_CTL0_CH1TSEL_SW << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_TACCR2 (DMA_CTL0_CH1TSEL_TACCR2 << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_TBCCR2 (DMA_CTL0_CH1TSEL_TBCCR2 << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_USART0_RX (DMA_CTL0_CH1TSEL_USART0_RX << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_USART0_TX (DMA_CTL0_CH1TSEL_USART0_TX << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_DAC12_0 (DMA_CTL0_CH1TSEL_DAC12_0 << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_ADC12x (DMA_CTL0_CH1TSEL_ADC12x << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_TACCR0 (DMA_CTL0_CH1TSEL_TACCR0 << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_TBCCR0 (DMA_CTL0_CH1TSEL_TBCCR0 << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_USART1_RX (DMA_CTL0_CH1TSEL_USART1_RX << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_USART1_TX (DMA_CTL0_CH1TSEL_USART1_TX << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_MULTIPLIER (DMA_CTL0_CH1TSEL_MULTIPLIER << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_NO_TRIGGER0 (DMA_CTL0_CH1TSEL_NO_TRIGGER0 << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_NO_TRIGGER1 (DMA_CTL0_CH1TSEL_NO_TRIGGER1 << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_DMA (DMA_CTL0_CH1TSEL_DMA << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_EXTERNAL (DMA_CTL0_CH1TSEL_EXTERNAL << DMA_CTL0_R_CH1TSEL_BIT)
/*-----------*/

/*-----------*/
#define DMA_CTL0_R_CH2TSEL_BIT ((uint8_t) 8U)

#define DMA_CTL0_CH2TSEL_MASK ((uint8_t) 0x0FU)
#define DMA_CTL0_CH2TSEL_SW ((uint8_t) 0x00U)
#define DMA_CTL0_CH2TSEL_TACCR2 ((uint8_t) 0x01U)
#define DMA_CTL0_CH2TSEL_TBCCR2 ((uint8_t) 0x02U)
#define DMA_CTL0_CH2TSEL_USART0_RX ((uint8_t) 0x03U)
#define DMA_CTL0_CH2TSEL_USART0_TX ((uint8_t) 0x04U)
#define DMA_CTL0_CH2TSEL_DAC12_0 ((uint8_t) 0x05U)
#define DMA_CTL0_CH2TSEL_ADC12x ((uint8_t) 0x06U)
#define DMA_CTL0_CH2TSEL_TACCR0 ((uint8_t) 0x07U)
#define DMA_CTL0_CH2TSEL_TBCCR0 ((uint8_t) 0x08U)
#define DMA_CTL0_CH2TSEL_USART1_RX ((uint8_t) 0x09U)
#define DMA_CTL0_CH2TSEL_USART1_TX ((uint8_t) 0x0AU)
#define DMA_CTL0_CH2TSEL_MULTIPLIER ((uint8_t) 0x0BU)
#define DMA_CTL0_CH2TSEL_NO_TRIGGER0 ((uint8_t) 0x0CU)
#define DMA_CTL0_CH2TSEL_NO_TRIGGER1 ((uint8_t) 0x0DU)
#define DMA_CTL0_CH2TSEL_DMA ((uint8_t) 0x0EU)
#define DMA_CTL0_CH2TSEL_EXTERNAL ((uint8_t) 0x0FU)

#define DMA_CTL0_R_CH2TSEL_MASK (DMA_CTL0_CH2TSEL_MASK << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_SW (DMA_CTL0_CH2TSEL_SW << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_TACCR2 (DMA_CTL0_CH2TSEL_TACCR2 << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_TBCCR2 (DMA_CTL0_CH2TSEL_TBCCR2 << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_USART0_RX (DMA_CTL0_CH2TSEL_USART0_RX << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_USART0_TX (DMA_CTL0_CH2TSEL_USART0_TX << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_DAC12_0 (DMA_CTL0_CH2TSEL_DAC12_0 << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_ADC12x (DMA_CTL0_CH2TSEL_ADC12x << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_TACCR0 (DMA_CTL0_CH2TSEL_TACCR0 << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_TBCCR0 (DMA_CTL0_CH2TSEL_TBCCR0 << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_USART1_RX (DMA_CTL0_CH2TSEL_USART1_RX << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_USART1_TX (DMA_CTL0_CH2TSEL_USART1_TX << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_MULTIPLIER (DMA_CTL0_CH2TSEL_MULTIPLIER << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_NO_TRIGGER0 (DMA_CTL0_CH2TSEL_NO_TRIGGER0 << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_NO_TRIGGER1 (DMA_CTL0_CH2TSEL_NO_TRIGGER1 << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_DMA (DMA_CTL0_CH2TSEL_DMA << DMA_CTL0_R_CH2TSEL_BIT)
#define DMA_CTL0_R_CH2TSEL_EXTERNAL (DMA_CTL0_CH2TSEL_EXTERNAL << DMA_CTL0_R_CH2TSEL_BIT)
/*-----------*/


#endif /* DMA_PERIPHERAL_REGISTERDEFINES_HEADER_DMA_REGISTERDEFINES_CTL0_H_ */
