/**
 *
 * @file TIMERB_RegisterDefines_CC_CTL.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 9 abr. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 9 abr. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_TIMERB_PERIPHERAL_REGISTERDEFINES_HEADER_TIMERB_REGISTERDEFINES_CC_CTL_H_
#define DRIVERLIB_TIMERB_PERIPHERAL_REGISTERDEFINES_HEADER_TIMERB_REGISTERDEFINES_CC_CTL_H_

#include "DriverLib/MCU/Header/MCU_Common.h"

/******************************************************************************************
 ************************************ 3 CC_CTL *********************************************
 ******************************************************************************************/
/*-----------*/
#define TIMERB_CC_CTL_R_IFG_BIT ((uint16_t) 0U)

#define TIMERB_CC_CTL_IFG_MASK ((uint16_t) 0x01U)
#define TIMERB_CC_CTL_IFG_NOOCCUR ((uint16_t) 0x00U)
#define TIMERB_CC_CTL_IFG_OCCUR ((uint16_t) 0x01U)

#define TIMERB_CC_CTL_R_IFG_MASK (TIMERB_CC_CTL_IFG_MASK << TIMERB_CC_CTL_R_IFG_BIT)
#define TIMERB_CC_CTL_R_IFG_NOOCCUR (TIMERB_CC_CTL_IFG_NOOCCUR << TIMERB_CC_CTL_R_IFG_BIT)
#define TIMERB_CC_CTL_R_IFG_OCCUR (TIMERB_CC_CTL_IFG_OCCUR << TIMERB_CC_CTL_R_IFG_BIT)
/*-----------*/

/*-----------*/
#define TIMERB_CC_CTL_R_COV_BIT ((uint16_t) 1U)

#define TIMERB_CC_CTL_COV_MASK ((uint16_t) 0x01U)
#define TIMERB_CC_CTL_COV_NOOCCUR ((uint16_t) 0x00U)
#define TIMERB_CC_CTL_COV_OCCUR ((uint16_t) 0x01U)

#define TIMERB_CC_CTL_R_COV_MASK (TIMERB_CC_CTL_COV_MASK << TIMERB_CC_CTL_R_COV_BIT)
#define TIMERB_CC_CTL_R_COV_NOOCCUR (TIMERB_CC_CTL_COV_NOOCCUR << TIMERB_CC_CTL_R_COV_BIT)
#define TIMERB_CC_CTL_R_COV_OCCUR (TIMERB_CC_CTL_COV_OCCUR << TIMERB_CC_CTL_R_COV_BIT)
/*-----------*/

/*-----------*/
#define TIMERB_CC_CTL_R_OUT_BIT ((uint16_t) 2U)

#define TIMERB_CC_CTL_OUT_MASK ((uint16_t) 0x01U)
#define TIMERB_CC_CTL_OUT_LOW ((uint16_t) 0x00U)
#define TIMERB_CC_CTL_OUT_HIGH ((uint16_t) 0x01U)

#define TIMERB_CC_CTL_R_OUT_MASK (TIMERB_CC_CTL_OUT_MASK << TIMERB_CC_CTL_R_OUT_BIT)
#define TIMERB_CC_CTL_R_OUT_LOW (TIMERB_CC_CTL_OUT_LOW << TIMERB_CC_CTL_R_OUT_BIT)
#define TIMERB_CC_CTL_R_OUT_HIGH (TIMERB_CC_CTL_OUT_HIGH << TIMERB_CC_CTL_R_OUT_BIT)
/*-----------*/

/*-----------*/
#define TIMERB_CC_CTL_R_CCI_BIT ((uint16_t) 3U)

#define TIMERB_CC_CTL_CCI_MASK ((uint16_t) 0x01U)
#define TIMERB_CC_CTL_CCI_LOW ((uint16_t) 0x00U)
#define TIMERB_CC_CTL_CCI_HIGH ((uint16_t) 0x01U)

#define TIMERB_CC_CTL_R_CCI_MASK (TIMERB_CC_CTL_CCI_MASK << TIMERB_CC_CTL_R_CCI_BIT)
#define TIMERB_CC_CTL_R_CCI_LOW (TIMERB_CC_CTL_CCI_LOW << TIMERB_CC_CTL_R_CCI_BIT)
#define TIMERB_CC_CTL_R_CCI_HIGH (TIMERB_CC_CTL_CCI_HIGH << TIMERB_CC_CTL_R_CCI_BIT)
/*-----------*/

/*-----------*/
#define TIMERB_CC_CTL_R_IE_BIT ((uint16_t) 4U)

#define TIMERB_CC_CTL_IE_MASK ((uint16_t) 0x01U)
#define TIMERB_CC_CTL_IE_DIS ((uint16_t) 0x00U)
#define TIMERB_CC_CTL_IE_ENA ((uint16_t) 0x01U)

#define TIMERB_CC_CTL_R_IE_MASK (TIMERB_CC_CTL_IE_MASK << TIMERB_CC_CTL_R_IE_BIT)
#define TIMERB_CC_CTL_R_IE_DIS (TIMERB_CC_CTL_IE_DIS << TIMERB_CC_CTL_R_IE_BIT)
#define TIMERB_CC_CTL_R_IE_ENA (TIMERB_CC_CTL_IE_ENA << TIMERB_CC_CTL_R_IE_BIT)
/*-----------*/

/*-----------*/
#define TIMERB_CC_CTL_R_OUTMOD_BIT ((uint16_t) 5U)

#define TIMERB_CC_CTL_OUTMOD_MASK ((uint16_t) 0x07U)
#define TIMERB_CC_CTL_OUTMOD_OUT ((uint16_t) 0x00U)
#define TIMERB_CC_CTL_OUTMOD_SET ((uint16_t) 0x01U)
#define TIMERB_CC_CTL_OUTMOD_TOGGLE_RESET ((uint16_t) 0x02U)
#define TIMERB_CC_CTL_OUTMOD_SET_RESET ((uint16_t) 0x03U)
#define TIMERB_CC_CTL_OUTMOD_TOGGLE ((uint16_t) 0x04U)
#define TIMERB_CC_CTL_OUTMOD_RESET ((uint16_t) 0x05U)
#define TIMERB_CC_CTL_OUTMOD_TOGGLE_SET ((uint16_t) 0x06U)
#define TIMERB_CC_CTL_OUTMOD_RESET_SET ((uint16_t) 0x07U)

#define TIMERB_CC_CTL_R_OUTMOD_MASK (TIMERB_CC_CTL_OUTMOD_MASK << TIMERB_CC_CTL_R_OUTMOD_BIT)
#define TIMERB_CC_CTL_R_OUTMOD_OUT (TIMERB_CC_CTL_OUTMOD_OUT << TIMERB_CC_CTL_R_OUTMOD_BIT)
#define TIMERB_CC_CTL_R_OUTMOD_SET (TIMERB_CC_CTL_OUTMOD_SET << TIMERB_CC_CTL_R_OUTMOD_BIT)
#define TIMERB_CC_CTL_R_OUTMOD_TOGGLE_RESET (TIMERB_CC_CTL_OUTMOD_TOGGLE_RESET << TIMERB_CC_CTL_R_OUTMOD_BIT)
#define TIMERB_CC_CTL_R_OUTMOD_SET_RESET (TIMERB_CC_CTL_OUTMOD_SET_RESET << TIMERB_CC_CTL_R_OUTMOD_BIT)
#define TIMERB_CC_CTL_R_OUTMOD_TOGGLE (TIMERB_CC_CTL_OUTMOD_TOGGLE << TIMERB_CC_CTL_R_OUTMOD_BIT)
#define TIMERB_CC_CTL_R_OUTMOD_RESET (TIMERB_CC_CTL_OUTMOD_RESET << TIMERB_CC_CTL_R_OUTMOD_BIT)
#define TIMERB_CC_CTL_R_OUTMOD_TOGGLE_SET (TIMERB_CC_CTL_OUTMOD_TOGGLE_SET << TIMERB_CC_CTL_R_OUTMOD_BIT)
#define TIMERB_CC_CTL_R_OUTMOD_RESET_SET (TIMERB_CC_CTL_OUTMOD_RESET_SET << TIMERB_CC_CTL_R_OUTMOD_BIT)
/*-----------*/

/*-----------*/
#define TIMERB_CC_CTL_R_CAP_BIT ((uint16_t) 8U)

#define TIMERB_CC_CTL_CAP_MASK ((uint16_t) 0x01U)
#define TIMERB_CC_CTL_CAP_COMPARE ((uint16_t) 0x00U)
#define TIMERB_CC_CTL_CAP_CAPTURE ((uint16_t) 0x01U)

#define TIMERB_CC_CTL_R_CAP_MASK (TIMERB_CC_CTL_CAP_MASK << TIMERB_CC_CTL_R_CAP_BIT)
#define TIMERB_CC_CTL_R_CAP_COMPARE (TIMERB_CC_CTL_CAP_COMPARE << TIMERB_CC_CTL_R_CAP_BIT)
#define TIMERB_CC_CTL_R_CAP_CAPTURE (TIMERB_CC_CTL_CAP_CAPTURE << TIMERB_CC_CTL_R_CAP_BIT)
/*-----------*/

/*-----------*/
#define TIMERB_CC_CTL_R_CLLD_BIT ((uint16_t) 9U)

#define TIMERB_CC_CTL_CLLD_MASK ((uint16_t) 0x03U)
#define TIMERB_CC_CTL_CLLD_IMMEDIATE ((uint16_t) 0x00U)
#define TIMERB_CC_CTL_CLLD_OV ((uint16_t) 0x01U)
#define TIMERB_CC_CTL_CLLD_OV_CCR0 ((uint16_t) 0x02U)
#define TIMERB_CC_CTL_CLLD_CCRx ((uint16_t) 0x03U)

#define TIMERB_CC_CTL_R_CLLD_MASK (TIMERB_CC_CTL_CLLD_MASK << TIMERB_CC_CTL_R_CLLD_BIT)
#define TIMERB_CC_CTL_R_CLLD_IMMEDIATE (TIMERB_CC_CTL_CLLD_IMMEDIATE << TIMERB_CC_CTL_R_CLLD_BIT)
#define TIMERB_CC_CTL_R_CLLD_OV (TIMERB_CC_CTL_CLLD_OV << TIMERB_CC_CTL_R_CLLD_BIT)
#define TIMERB_CC_CTL_R_CLLD_OV_CCR0 (TIMERB_CC_CTL_CLLD_OV_CCR0 << TIMERB_CC_CTL_R_CLLD_BIT)
#define TIMERB_CC_CTL_R_CLLD_CCRx (TIMERB_CC_CTL_CLLD_CCRx << TIMERB_CC_CTL_R_CLLD_BIT)
/*-----------*/

/*-----------*/
#define TIMERB_CC_CTL_R_SCS_BIT ((uint16_t) 11U)

#define TIMERB_CC_CTL_SCS_MASK ((uint16_t) 0x01U)
#define TIMERB_CC_CTL_SCS_ASYNC ((uint16_t) 0x00U)
#define TIMERB_CC_CTL_SCS_SYNC ((uint16_t) 0x01U)

#define TIMERB_CC_CTL_R_SCS_MASK (TIMERB_CC_CTL_SCS_MASK << TIMERB_CC_CTL_R_SCS_BIT)
#define TIMERB_CC_CTL_R_SCS_ASYNC (TIMERB_CC_CTL_SCS_ASYNC << TIMERB_CC_CTL_R_SCS_BIT)
#define TIMERB_CC_CTL_R_SCS_SYNC (TIMERB_CC_CTL_SCS_SYNC << TIMERB_CC_CTL_R_SCS_BIT)
/*-----------*/

/*-----------*/
#define TIMERB_CC_CTL_R_CCIS_BIT ((uint16_t) 12U)

#define TIMERB_CC_CTL_CCIS_MASK ((uint16_t) 0x03U)
#define TIMERB_CC_CTL_CCIS_CCIA ((uint16_t) 0x00U)
#define TIMERB_CC_CTL_CCIS_CCIB ((uint16_t) 0x01U)
#define TIMERB_CC_CTL_CCIS_GND ((uint16_t) 0x02U)
#define TIMERB_CC_CTL_CCIS_VCC ((uint16_t) 0x03U)

#define TIMERB_CC_CTL_R_CCIS_MASK (TIMERB_CC_CTL_CCIS_MASK << TIMERB_CC_CTL_R_CCIS_BIT)
#define TIMERB_CC_CTL_R_CCIS_CCIA (TIMERB_CC_CTL_CCIS_CCIA << TIMERB_CC_CTL_R_CCIS_BIT)
#define TIMERB_CC_CTL_R_CCIS_CCIB (TIMERB_CC_CTL_CCIS_CCIB << TIMERB_CC_CTL_R_CCIS_BIT)
#define TIMERB_CC_CTL_R_CCIS_GND (TIMERB_CC_CTL_CCIS_GND << TIMERB_CC_CTL_R_CCIS_BIT)
#define TIMERB_CC_CTL_R_CCIS_VCC (TIMERB_CC_CTL_CCIS_VCC << TIMERB_CC_CTL_R_CCIS_BIT)
/*-----------*/

/*-----------*/
#define TIMERB_CC_CTL_R_CM_BIT ((uint16_t) 14U)

#define TIMERB_CC_CTL_CM_MASK ((uint16_t) 0x03U)
#define TIMERB_CC_CTL_CM_NONE ((uint16_t) 0x00U)
#define TIMERB_CC_CTL_CM_RISING ((uint16_t) 0x01U)
#define TIMERB_CC_CTL_CM_FALLING ((uint16_t) 0x02U)
#define TIMERB_CC_CTL_CM_BOTH ((uint16_t) 0x03U)

#define TIMERB_CC_CTL_R_CM_MASK (TIMERB_CC_CTL_CM_MASK << TIMERB_CC_CTL_R_CM_BIT)
#define TIMERB_CC_CTL_R_CM_NONE (TIMERB_CC_CTL_CM_NONE << TIMERB_CC_CTL_R_CM_BIT)
#define TIMERB_CC_CTL_R_CM_RISING (TIMERB_CC_CTL_CM_RISING << TIMERB_CC_CTL_R_CM_BIT)
#define TIMERB_CC_CTL_R_CM_FALLING (TIMERB_CC_CTL_CM_FALLING << TIMERB_CC_CTL_R_CM_BIT)
#define TIMERB_CC_CTL_R_CM_BOTH (TIMERB_CC_CTL_CM_BOTH << TIMERB_CC_CTL_R_CM_BIT)
/*-----------*/

#endif /* DRIVERLIB_TIMERB_PERIPHERAL_REGISTERDEFINES_HEADER_TIMERB_REGISTERDEFINES_CC_CTL_H_ */
