/**
 *
 * @file TIMERA_RegisterDefines_CC_CTL.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 9 abr. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 9 abr. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_TIMERA_PERIPHERAL_REGISTERDEFINES_HEADER_TIMERA_REGISTERDEFINES_CC_CTL_H_
#define DRIVERLIB_TIMERA_PERIPHERAL_REGISTERDEFINES_HEADER_TIMERA_REGISTERDEFINES_CC_CTL_H_

#include "DriverLib/MCU/Header/MCU_Common.h"

/******************************************************************************************
 ************************************ 3 CC_CTL *********************************************
 ******************************************************************************************/
/*-----------*/
#define TIMERA_CC_CTL_R_IFG_BIT ((uint16_t) 0U)

#define TIMERA_CC_CTL_IFG_MASK ((uint16_t) 0x01U)
#define TIMERA_CC_CTL_IFG_NOOCCUR ((uint16_t) 0x00U)
#define TIMERA_CC_CTL_IFG_OCCUR ((uint16_t) 0x01U)

#define TIMERA_CC_CTL_R_IFG_MASK (TIMERA_CC_CTL_IFG_MASK << TIMERA_CC_CTL_R_IFG_BIT)
#define TIMERA_CC_CTL_R_IFG_NOOCCUR (TIMERA_CC_CTL_IFG_NOOCCUR << TIMERA_CC_CTL_R_IFG_BIT)
#define TIMERA_CC_CTL_R_IFG_OCCUR (TIMERA_CC_CTL_IFG_OCCUR << TIMERA_CC_CTL_R_IFG_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_COV_BIT ((uint16_t) 1U)

#define TIMERA_CC_CTL_COV_MASK ((uint16_t) 0x01U)
#define TIMERA_CC_CTL_COV_NOOCCUR ((uint16_t) 0x00U)
#define TIMERA_CC_CTL_COV_OCCUR ((uint16_t) 0x01U)

#define TIMERA_CC_CTL_R_COV_MASK (TIMERA_CC_CTL_COV_MASK << TIMERA_CC_CTL_R_COV_BIT)
#define TIMERA_CC_CTL_R_COV_NOOCCUR (TIMERA_CC_CTL_COV_NOOCCUR << TIMERA_CC_CTL_R_COV_BIT)
#define TIMERA_CC_CTL_R_COV_OCCUR (TIMERA_CC_CTL_COV_OCCUR << TIMERA_CC_CTL_R_COV_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_OUT_BIT ((uint16_t) 2U)

#define TIMERA_CC_CTL_OUT_MASK ((uint16_t) 0x01U)
#define TIMERA_CC_CTL_OUT_LOW ((uint16_t) 0x00U)
#define TIMERA_CC_CTL_OUT_HIGH ((uint16_t) 0x01U)

#define TIMERA_CC_CTL_R_OUT_MASK (TIMERA_CC_CTL_OUT_MASK << TIMERA_CC_CTL_R_OUT_BIT)
#define TIMERA_CC_CTL_R_OUT_LOW (TIMERA_CC_CTL_OUT_LOW << TIMERA_CC_CTL_R_OUT_BIT)
#define TIMERA_CC_CTL_R_OUT_HIGH (TIMERA_CC_CTL_OUT_HIGH << TIMERA_CC_CTL_R_OUT_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_CCI_BIT ((uint16_t) 3U)

#define TIMERA_CC_CTL_CCI_MASK ((uint16_t) 0x01U)
#define TIMERA_CC_CTL_CCI_LOW ((uint16_t) 0x00U)
#define TIMERA_CC_CTL_CCI_HIGH ((uint16_t) 0x01U)

#define TIMERA_CC_CTL_R_CCI_MASK (TIMERA_CC_CTL_CCI_MASK << TIMERA_CC_CTL_R_CCI_BIT)
#define TIMERA_CC_CTL_R_CCI_LOW (TIMERA_CC_CTL_CCI_LOW << TIMERA_CC_CTL_R_CCI_BIT)
#define TIMERA_CC_CTL_R_CCI_HIGH (TIMERA_CC_CTL_CCI_HIGH << TIMERA_CC_CTL_R_CCI_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_IE_BIT ((uint16_t) 4U)

#define TIMERA_CC_CTL_IE_MASK ((uint16_t) 0x01U)
#define TIMERA_CC_CTL_IE_DIS ((uint16_t) 0x00U)
#define TIMERA_CC_CTL_IE_ENA ((uint16_t) 0x01U)

#define TIMERA_CC_CTL_R_IE_MASK (TIMERA_CC_CTL_IE_MASK << TIMERA_CC_CTL_R_IE_BIT)
#define TIMERA_CC_CTL_R_IE_DIS (TIMERA_CC_CTL_IE_DIS << TIMERA_CC_CTL_R_IE_BIT)
#define TIMERA_CC_CTL_R_IE_ENA (TIMERA_CC_CTL_IE_ENA << TIMERA_CC_CTL_R_IE_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_OUTMOD_BIT ((uint16_t) 5U)

#define TIMERA_CC_CTL_OUTMOD_MASK ((uint16_t) 0x07U)
#define TIMERA_CC_CTL_OUTMOD_OUT ((uint16_t) 0x00U)
#define TIMERA_CC_CTL_OUTMOD_SET ((uint16_t) 0x01U)
#define TIMERA_CC_CTL_OUTMOD_TOGGLE_RESET ((uint16_t) 0x02U)
#define TIMERA_CC_CTL_OUTMOD_SET_RESET ((uint16_t) 0x03U)
#define TIMERA_CC_CTL_OUTMOD_TOGGLE ((uint16_t) 0x04U)
#define TIMERA_CC_CTL_OUTMOD_RESET ((uint16_t) 0x05U)
#define TIMERA_CC_CTL_OUTMOD_TOGGLE_SET ((uint16_t) 0x06U)
#define TIMERA_CC_CTL_OUTMOD_RESET_SET ((uint16_t) 0x07U)

#define TIMERA_CC_CTL_R_OUTMOD_MASK (TIMERA_CC_CTL_OUTMOD_MASK << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_OUT (TIMERA_CC_CTL_OUTMOD_OUT << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_SET (TIMERA_CC_CTL_OUTMOD_SET << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_TOGGLE_RESET (TIMERA_CC_CTL_OUTMOD_TOGGLE_RESET << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_SET_RESET (TIMERA_CC_CTL_OUTMOD_SET_RESET << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_TOGGLE (TIMERA_CC_CTL_OUTMOD_TOGGLE << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_RESET (TIMERA_CC_CTL_OUTMOD_RESET << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_TOGGLE_SET (TIMERA_CC_CTL_OUTMOD_TOGGLE_SET << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_RESET_SET (TIMERA_CC_CTL_OUTMOD_RESET_SET << TIMERA_CC_CTL_R_OUTMOD_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_CAP_BIT ((uint16_t) 8U)

#define TIMERA_CC_CTL_CAP_MASK ((uint16_t) 0x01U)
#define TIMERA_CC_CTL_CAP_COMPARE ((uint16_t) 0x00U)
#define TIMERA_CC_CTL_CAP_CAPTURE ((uint16_t) 0x01U)

#define TIMERA_CC_CTL_R_CAP_MASK (TIMERA_CC_CTL_CAP_MASK << TIMERA_CC_CTL_R_CAP_BIT)
#define TIMERA_CC_CTL_R_CAP_COMPARE (TIMERA_CC_CTL_CAP_COMPARE << TIMERA_CC_CTL_R_CAP_BIT)
#define TIMERA_CC_CTL_R_CAP_CAPTURE (TIMERA_CC_CTL_CAP_CAPTURE << TIMERA_CC_CTL_R_CAP_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_SCCI_BIT ((uint16_t) 10U)

#define TIMERA_CC_CTL_SCCI_MASK ((uint16_t) 0x01U)
#define TIMERA_CC_CTL_SCCI_LOW ((uint16_t) 0x00U)
#define TIMERA_CC_CTL_SCCI_HIGH ((uint16_t) 0x01U)

#define TIMERA_CC_CTL_R_SCCI_MASK (TIMERA_CC_CTL_SCCI_MASK << TIMERA_CC_CTL_R_SCCI_BIT)
#define TIMERA_CC_CTL_R_SCCI_LOW (TIMERA_CC_CTL_SCCI_LOW << TIMERA_CC_CTL_R_SCCI_BIT)
#define TIMERA_CC_CTL_R_SCCI_HIGH (TIMERA_CC_CTL_SCCI_HIGH << TIMERA_CC_CTL_R_SCCI_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_SCS_BIT ((uint16_t) 11U)

#define TIMERA_CC_CTL_SCS_MASK ((uint16_t) 0x01U)
#define TIMERA_CC_CTL_SCS_ASYNC ((uint16_t) 0x00U)
#define TIMERA_CC_CTL_SCS_SYNC ((uint16_t) 0x01U)

#define TIMERA_CC_CTL_R_SCS_MASK (TIMERA_CC_CTL_SCS_MASK << TIMERA_CC_CTL_R_SCS_BIT)
#define TIMERA_CC_CTL_R_SCS_ASYNC (TIMERA_CC_CTL_SCS_ASYNC << TIMERA_CC_CTL_R_SCS_BIT)
#define TIMERA_CC_CTL_R_SCS_SYNC (TIMERA_CC_CTL_SCS_SYNC << TIMERA_CC_CTL_R_SCS_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_CCIS_BIT ((uint16_t) 12U)

#define TIMERA_CC_CTL_CCIS_MASK ((uint16_t) 0x03U)
#define TIMERA_CC_CTL_CCIS_CCIA ((uint16_t) 0x00U)
#define TIMERA_CC_CTL_CCIS_CCIB ((uint16_t) 0x01U)
#define TIMERA_CC_CTL_CCIS_GND ((uint16_t) 0x02U)
#define TIMERA_CC_CTL_CCIS_VCC ((uint16_t) 0x03U)

#define TIMERA_CC_CTL_R_CCIS_MASK (TIMERA_CC_CTL_CCIS_MASK << TIMERA_CC_CTL_R_CCIS_BIT)
#define TIMERA_CC_CTL_R_CCIS_CCIA (TIMERA_CC_CTL_CCIS_CCIA << TIMERA_CC_CTL_R_CCIS_BIT)
#define TIMERA_CC_CTL_R_CCIS_CCIB (TIMERA_CC_CTL_CCIS_CCIB << TIMERA_CC_CTL_R_CCIS_BIT)
#define TIMERA_CC_CTL_R_CCIS_GND (TIMERA_CC_CTL_CCIS_GND << TIMERA_CC_CTL_R_CCIS_BIT)
#define TIMERA_CC_CTL_R_CCIS_VCC (TIMERA_CC_CTL_CCIS_VCC << TIMERA_CC_CTL_R_CCIS_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_CM_BIT ((uint16_t) 14U)

#define TIMERA_CC_CTL_CM_MASK ((uint16_t) 0x03U)
#define TIMERA_CC_CTL_CM_NONE ((uint16_t) 0x00U)
#define TIMERA_CC_CTL_CM_RISING ((uint16_t) 0x01U)
#define TIMERA_CC_CTL_CM_FALLING ((uint16_t) 0x02U)
#define TIMERA_CC_CTL_CM_BOTH ((uint16_t) 0x03U)

#define TIMERA_CC_CTL_R_CM_MASK (TIMERA_CC_CTL_CM_MASK << TIMERA_CC_CTL_R_CM_BIT)
#define TIMERA_CC_CTL_R_CM_NONE (TIMERA_CC_CTL_CM_NONE << TIMERA_CC_CTL_R_CM_BIT)
#define TIMERA_CC_CTL_R_CM_RISING (TIMERA_CC_CTL_CM_RISING << TIMERA_CC_CTL_R_CM_BIT)
#define TIMERA_CC_CTL_R_CM_FALLING (TIMERA_CC_CTL_CM_FALLING << TIMERA_CC_CTL_R_CM_BIT)
#define TIMERA_CC_CTL_R_CM_BOTH (TIMERA_CC_CTL_CM_BOTH << TIMERA_CC_CTL_R_CM_BIT)
/*-----------*/

#endif /* DRIVERLIB_TIMERA_PERIPHERAL_REGISTERDEFINES_HEADER_TIMERA_REGISTERDEFINES_CC_CTL_H_ */
